name: get_highway_features

channels:
  - esri
  - conda-forge

dependencies:
  - appnope
  - arcgis
  - arcgis-mapping
  - black>=21
  - h3-py
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pip
  - pytest
  - tqdm
  - pip:
    - build
    - bump2version
    - mkdocs
    - mkdocs-glightbox
    - mkdocs-include-markdown-plugin
    - mkdocs-jupyter
    - mkdocs-material
    - mkdocstrings[python]>=0.18
    - twine
